name: build

on:
  push:
    paths-ignore:
    - '.vscode/**'
    - '.editorconfig'
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Setup node.js
      uses: actions/setup-node@v5
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
    - name: Prepare build environment
      shell: bash
      run: |
        npm install --loglevel notice --no-progress
    - name: Build
      shell: bash
      run: |
        npm run-script "build:release" --loglevel notice --no-progress
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          tmp/out/bin/**.*
    - name: Archive logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: |
          build.log
          .tmp/npm-cache/_logs/**.log
        retention-days: 2
    - name: Deploy
      if: startsWith(github.event.ref, 'refs/tags/v')
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish
